### ISSUE TITLE
Possible Conflict with Choke Effect from Infernal Mobs

### ISSUE THREAD

**Issue by Camawama** [Darkhax-Minecraft/Better-Drowning#1]
I just thought I'd report this here, even though I haven't been able to narrow it down to your mod. Whenever an infernal mob causes the choke effect on someone (makes them lose air even above ground) there is a chance that the player will get a weird glitch where the bubbles pop and disappear and don't come back at all causing the player to drown on land. When the player dies they would no longer have bubbles appear while underwater thus granting the player the ability to swim forever without drowning. Strange bug, I know. I'm hoping that it's an easy fix!

**Comment by Darkhax** [comment]
Were you able to track this issue down after?
