### ISSUE TITLE
[Suggestion] Eating Underwater

### ISSUE THREAD

**Issue by Zeklo** [Darkhax-Minecraft/Better-Drowning#2]
How about preventing/losing air bubbles/drowning on attempting to eat while underwater?
Seems to fit the theme of this mod.

**Comment by Darkhax** [comment]
Thanks for the feature request. Unfortunately this would introduce a huge game breaking bug where you can hold down items that can always be eaten (like a golden apple or chorus fruit), not finish eating them, and have infinite air.
