### ISSUE TITLE
Problems found

### ISSUE THREAD

**Issue by jpaulo-rb** [Darkhax-Minecraft/Better-Drowning#3]
Hi, I think I found a little problem here. Sometimes the rendering of underwater animals doesn't work, they just disappear. I didn't test it with all the mobs, but it happened with the Sea Serpent and also with the Hippocampus of the Ice and Fire mod.
After removing the mod, it returned to normal.

**Comment by Darkhax** [comment]
The issue you described sounds like incorrect rendering bounds and pop-in with the Ice and Fire mod. This mod has no complex or ambiguous rendering code that could introduce this problem.
